CREATE TABLE user (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(30) NOT NULL,
	pwd VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	age INT(3) NOT NULL
)